// flow-typed signature: 1f327d5c30ee3df049377341fab144b0
// flow-typed version: <<STUB>>/babel-plugin-module-alias_v^1.6.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-module-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-module-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-module-alias/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-module-alias/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-module-alias/lib/index'>;
}
