// flow-typed signature: e3bdd1441bedd850fe2c9098367dac9b
// flow-typed version: <<STUB>>/babel-plugin-transform-remove-debugger_v^6.8.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-remove-debugger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-remove-debugger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-remove-debugger/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-remove-debugger/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-remove-debugger/lib/index'>;
}
