// flow-typed signature: b110ee107827c39e74162cff133493c4
// flow-typed version: <<STUB>>/eslint-nibble-ignore_v^3.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-nibble-ignore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-nibble-ignore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-nibble-ignore/bin/eslint-nibble' {
  declare module.exports: any;
}

declare module 'eslint-nibble-ignore/lib/cli' {
  declare module.exports: any;
}

declare module 'eslint-nibble-ignore/lib/config/formatters' {
  declare module.exports: any;
}

declare module 'eslint-nibble-ignore/lib/config/options' {
  declare module.exports: any;
}

declare module 'eslint-nibble-ignore/lib/nibbler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-nibble-ignore/bin/eslint-nibble.js' {
  declare module.exports: $Exports<'eslint-nibble-ignore/bin/eslint-nibble'>;
}
declare module 'eslint-nibble-ignore/index' {
  declare module.exports: $Exports<'eslint-nibble-ignore'>;
}
declare module 'eslint-nibble-ignore/index.js' {
  declare module.exports: $Exports<'eslint-nibble-ignore'>;
}
declare module 'eslint-nibble-ignore/lib/cli.js' {
  declare module.exports: $Exports<'eslint-nibble-ignore/lib/cli'>;
}
declare module 'eslint-nibble-ignore/lib/config/formatters.js' {
  declare module.exports: $Exports<'eslint-nibble-ignore/lib/config/formatters'>;
}
declare module 'eslint-nibble-ignore/lib/config/options.js' {
  declare module.exports: $Exports<'eslint-nibble-ignore/lib/config/options'>;
}
declare module 'eslint-nibble-ignore/lib/nibbler.js' {
  declare module.exports: $Exports<'eslint-nibble-ignore/lib/nibbler'>;
}
