// flow-typed signature: 53655b7cfa75924cb9a30f792b22e3c7
// flow-typed version: <<STUB>>/jasmine-node_vx/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-node/lib/jasmine-node/auto-test' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/cli' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/file-finder' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/jasmine-1.3.1' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/jasmine-loader' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/jasmine/boot' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/jasmine/jasmine-2.0.0' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/reporter' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/runner' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/helper_spec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/nested' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/nested.js/NestedSpec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/nested/NestedSpec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/nested/uber-nested/UberNestedSpec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/reporter_spec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/SampleSpec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/Test.Test' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/TestSpec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/TimerSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-node/index' {
  declare module.exports: $Exports<'jasmine-node'>;
}
declare module 'jasmine-node/index.js' {
  declare module.exports: $Exports<'jasmine-node'>;
}
declare module 'jasmine-node/lib/jasmine-node/auto-test.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/auto-test'>;
}
declare module 'jasmine-node/lib/jasmine-node/cli.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/cli'>;
}
declare module 'jasmine-node/lib/jasmine-node/file-finder.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/file-finder'>;
}
declare module 'jasmine-node/lib/jasmine-node/jasmine-1.3.1.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/jasmine-1.3.1'>;
}
declare module 'jasmine-node/lib/jasmine-node/jasmine-loader.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/jasmine-loader'>;
}
declare module 'jasmine-node/lib/jasmine-node/jasmine/boot.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/jasmine/boot'>;
}
declare module 'jasmine-node/lib/jasmine-node/jasmine/jasmine-2.0.0.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/jasmine/jasmine-2.0.0'>;
}
declare module 'jasmine-node/lib/jasmine-node/reporter.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/reporter'>;
}
declare module 'jasmine-node/lib/jasmine-node/runner.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/runner'>;
}
declare module 'jasmine-node/spec/helper_spec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/helper_spec'>;
}
declare module 'jasmine-node/spec/nested.js' {
  declare module.exports: $Exports<'jasmine-node/spec/nested'>;
}
declare module 'jasmine-node/spec/nested.js/NestedSpec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/nested.js/NestedSpec'>;
}
declare module 'jasmine-node/spec/nested/NestedSpec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/nested/NestedSpec'>;
}
declare module 'jasmine-node/spec/nested/uber-nested/UberNestedSpec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/nested/uber-nested/UberNestedSpec'>;
}
declare module 'jasmine-node/spec/reporter_spec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/reporter_spec'>;
}
declare module 'jasmine-node/spec/SampleSpec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/SampleSpec'>;
}
declare module 'jasmine-node/spec/Test.Test.js' {
  declare module.exports: $Exports<'jasmine-node/spec/Test.Test'>;
}
declare module 'jasmine-node/spec/TestSpec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/TestSpec'>;
}
declare module 'jasmine-node/spec/TimerSpec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/TimerSpec'>;
}
