// flow-typed signature: 62d64a2902c89816dc23eb30e9e69d26
// flow-typed version: <<STUB>>/jasmine-node_vx/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-node/lib/jasmine-node/async-callback' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/autotest' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/cli' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/cs' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/index' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/jasmine-1.3.1' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/reporter' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/requirejs-runner' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/requirejs-spec-loader' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/requirejs-wrapper-template' {
  declare module.exports: any;
}

declare module 'jasmine-node/lib/jasmine-node/spec-collection' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec-requirejs-coffee/requirejs-setup' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec-requirejs/requirejs-setup' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec-requirejs/requirejs-wrapper-template' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec-requirejs/requirejs.spec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec-requirejs/requirejs.sut' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/async-callback_spec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/helper_spec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/nested' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/nested.js/NestedSpec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/nested/NestedSpec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/nested/uber-nested/UberNestedSpec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/reporter_spec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/sample_helper' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/SampleSpecs' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/TestSpec' {
  declare module.exports: any;
}

declare module 'jasmine-node/spec/TimerSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-node/lib/jasmine-node/async-callback.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/async-callback'>;
}
declare module 'jasmine-node/lib/jasmine-node/autotest.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/autotest'>;
}
declare module 'jasmine-node/lib/jasmine-node/cli.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/cli'>;
}
declare module 'jasmine-node/lib/jasmine-node/cs.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/cs'>;
}
declare module 'jasmine-node/lib/jasmine-node/index.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/index'>;
}
declare module 'jasmine-node/lib/jasmine-node/jasmine-1.3.1.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/jasmine-1.3.1'>;
}
declare module 'jasmine-node/lib/jasmine-node/reporter.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/reporter'>;
}
declare module 'jasmine-node/lib/jasmine-node/requirejs-runner.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/requirejs-runner'>;
}
declare module 'jasmine-node/lib/jasmine-node/requirejs-spec-loader.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/requirejs-spec-loader'>;
}
declare module 'jasmine-node/lib/jasmine-node/requirejs-wrapper-template.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/requirejs-wrapper-template'>;
}
declare module 'jasmine-node/lib/jasmine-node/spec-collection.js' {
  declare module.exports: $Exports<'jasmine-node/lib/jasmine-node/spec-collection'>;
}
declare module 'jasmine-node/spec-requirejs-coffee/requirejs-setup.js' {
  declare module.exports: $Exports<'jasmine-node/spec-requirejs-coffee/requirejs-setup'>;
}
declare module 'jasmine-node/spec-requirejs/requirejs-setup.js' {
  declare module.exports: $Exports<'jasmine-node/spec-requirejs/requirejs-setup'>;
}
declare module 'jasmine-node/spec-requirejs/requirejs-wrapper-template.js' {
  declare module.exports: $Exports<'jasmine-node/spec-requirejs/requirejs-wrapper-template'>;
}
declare module 'jasmine-node/spec-requirejs/requirejs.spec.js' {
  declare module.exports: $Exports<'jasmine-node/spec-requirejs/requirejs.spec'>;
}
declare module 'jasmine-node/spec-requirejs/requirejs.sut.js' {
  declare module.exports: $Exports<'jasmine-node/spec-requirejs/requirejs.sut'>;
}
declare module 'jasmine-node/spec/async-callback_spec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/async-callback_spec'>;
}
declare module 'jasmine-node/spec/helper_spec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/helper_spec'>;
}
declare module 'jasmine-node/spec/nested.js' {
  declare module.exports: $Exports<'jasmine-node/spec/nested'>;
}
declare module 'jasmine-node/spec/nested.js/NestedSpec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/nested.js/NestedSpec'>;
}
declare module 'jasmine-node/spec/nested/NestedSpec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/nested/NestedSpec'>;
}
declare module 'jasmine-node/spec/nested/uber-nested/UberNestedSpec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/nested/uber-nested/UberNestedSpec'>;
}
declare module 'jasmine-node/spec/reporter_spec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/reporter_spec'>;
}
declare module 'jasmine-node/spec/sample_helper.js' {
  declare module.exports: $Exports<'jasmine-node/spec/sample_helper'>;
}
declare module 'jasmine-node/spec/SampleSpecs.js' {
  declare module.exports: $Exports<'jasmine-node/spec/SampleSpecs'>;
}
declare module 'jasmine-node/spec/TestSpec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/TestSpec'>;
}
declare module 'jasmine-node/spec/TimerSpec.js' {
  declare module.exports: $Exports<'jasmine-node/spec/TimerSpec'>;
}
